model_args:
  device: cuda
  img_size: 1888
  conf_thres: 0.25
  iou_thres: 0.45
  pdf_dpi: 200
  layout_weight: literaturegpt/document_loaders/pdf_extract_kit/models/Layout/model_final.pth
  mfd_weight: literaturegpt/document_loaders/pdf_extract_kit/models/MFD/weights.pt
  mfr_weight: literaturegpt/document_loaders/pdf_extract_kit/models/MFR/UniMERNet
